name: Checkout Workflow
on: [push]
jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -la
      - uses: actions/checkout@v3
      - name: List Files After
        run: ls -la
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -la
      - name: Debug variables
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REPOSITORY: ${{github.repository}}"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}"
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List Files After
        run: ls -la  
