name: Checkout Workflow
on: [push]
jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before
        run: ls -la
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB.REPOSITORY.git"
          git featch origin
          git checkout main
      - name: List Files After
        run: ls -la  
