name: Concurrency 1
run-name: Concurrency 1 (${{ inputs.environment }})
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true
  
#Concurrency: concurrency-1 # This is a concurrency group name

#Concurrency:
#  group: concurrency-1
#  cancel-in-progress: true # This will cancel any in-progress jobs in the same group when a new job is triggered

concurrency:
  #group: ${{ github.event.inputs.environment }} # This is a concurrency group name based on the input environment 
  group: ${{ github-workflow }}-${{ github.event.inputs.environment }} # This is a concurrency group name based on the workflow name and input environmen
  cancel-in-progress: true # This will cancel any in-progress jobs in the same group when a new job is triggered
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        run: sleep 30