name: Environment Variables
on: [push]


jobs:
  env-vars-and-context:
    runs-on: ubuntu-latest
    steps:
      - name: Log ENV VAR
          run: echo $GITHUB_REF

      - name: Log Context
        run: echo '${{ github.ref }}'
      #- name: Print Environment Variables
      #  run: |
      #    echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
      #    echo "GITHUB_REF: $GITHUB_REF"
      #    echo "GITHUB_SHA: $GITHUB_SHA"
      #    echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
      #    echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
      #    echo "GITHUB_ACTOR: $GITHUB_ACTOR"
      #    echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
      #    echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
      #    echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
#
      #- name: Print Context Variables
      #  run: |
      #    echo "Context Variables:"
      #    echo "${{ toJson(github) }}"