name: Expressions & Contexts
on: [push, pull_request, issues, workflow_dispatch]

jobs:
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{ null}}
          echo ${{ 1 > 2}}
          echo ${{ 'string' == 'String'}}
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}

      - name: Contexts
        id: contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
          echo ${{ github.event_name }}
          echo ${{ github.repository }}
          echo ${{ github.actor }}
          echo ${{ github.sha }}
          echo ${{ github.ref }}
          echo ${{ github.workflow }}
          echo ${{ github.event.pull_request.title }}
          echo ${{ github.event.issue.title }}