name: Matrix
on: [push]


jobs:
  node-matrix:
    continue-on-error: false # This will cause the job to fail if any step fails 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14,15,16] 
        #runs-on: ubuntu-latest
        include:
          - os: ubuntu-latest
            is-ubuntu: true
          - os: macos-latest
            node-version: 15
          - experimental: false
          - os: ubuntu-latest
            node-version: 16
            experimental: true
          - os: ubuntu-latest
            node-version: 17
        exclude:
          - os: ubuntu-latest
            node-version: 14
        #run-parallel: 3 # This will run the jobs in parallel, up to 3 at a time 
      fail-fast: false # This will not stop the matrix if one job fails, it will continue running the other jobs 
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v 
