name: Pull Request Comment
on:
  pull_request_target:
    types: [opened]
jobs:
  pr-commnet:
    runs-on: ubuntu-latest
    permissions:
      #issues: read 
      issues: write  
    steps:
      - name: Comment on New PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const comment = `Hello @${pr.user.login}, thank you for opening this pull request!`;
            await github.rest.issues.createComment({
              issue_number: pr.number,
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for Contributing'
            });
    
    