name: Status Check Functions
on: [push]

jobs: 
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Step 2
        id: step-2 
        run: exit 1
      - name: Runs on step 2 Failure
        #if: failure()
        if: failure() && steps.step-2.conclusion == 'failure'
        #run: echo 'Runs only on failure'
        run: echo 'Step 2 has Failed'

      - name: Runs on Failure
      #if: failure()
        if: failure() 
        #run: echo 'Runs only on failure'
        run: echo 'Failure'
      - name: Runs on Success
      # This is not needed since the default is to run on success 
        if: success()
        run: echo 'Runs only on success'
      - name: Always Runs
        if: always()
        #if: success() || failure() || cancelled() # This is the same as `if: always()` 
        #if: success() || failure() # This is the same as before but without cacellation 
        run: echo 'Runs always, regardless of success or failure or cancellation'
      - name: Runs when Cancelled
        if: cancelled()
        run: echo 'Runs only when the job is cancelled'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
    
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2'